/**
 * generated by Xtext 2.10.0
 */
package org.emn.fil.boto.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.emn.fil.boto.ui.AbstractBotoLangUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BotoLangUiModule extends AbstractBotoLangUiModule {
  public BotoLangUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
