/*
 * generated by Xtext 2.10.0
 */
package org.emn.fil.boto.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractBotoLangValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.emn.fil.boto.botoLang.BotoLangPackage.eINSTANCE);
		return result;
	}
	
}
