/**
 * generated by Xtext 2.10.0
 */
package org.emn.fil.boto.ui.contentassist;

import org.emn.fil.boto.ui.contentassist.AbstractBotoLangProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class BotoLangProposalProvider extends AbstractBotoLangProposalProvider {
}
