/*
 * generated by Xtext 2.10.0
 */
package org.emn.fil.boto.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.emn.fil.boto.ui.internal.BotoActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BotoLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BotoActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BotoActivator.getInstance().getInjector(BotoActivator.ORG_EMN_FIL_BOTO_BOTOLANG);
	}
	
}
