/**
 * generated by Xtext 2.10.0
 */
package org.emn.fil.boto.botoLang;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.emn.fil.boto.botoLang.BotoLangFactory
 * @model kind="package"
 * @generated
 */
public interface BotoLangPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "botoLang";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.emn.org/fil/boto/BotoLang";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "botoLang";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BotoLangPackage eINSTANCE = org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl.init();

  /**
   * The meta object id for the '{@link org.emn.fil.boto.botoLang.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emn.fil.boto.botoLang.impl.ModelImpl
   * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Functions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__FUNCTIONS = 0;

  /**
   * The feature id for the '<em><b>Browsers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__BROWSERS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.emn.fil.boto.botoLang.impl.BrowserImpl <em>Browser</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emn.fil.boto.botoLang.impl.BrowserImpl
   * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getBrowser()
   * @generated
   */
  int BROWSER = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER__NAME = 0;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER__INSTRUCTIONS = 1;

  /**
   * The number of structural features of the '<em>Browser</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.emn.fil.boto.botoLang.impl.InstructionListImpl <em>Instruction List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emn.fil.boto.botoLang.impl.InstructionListImpl
   * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getInstructionList()
   * @generated
   */
  int INSTRUCTION_LIST = 2;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_LIST__INSTRUCTIONS = 0;

  /**
   * The number of structural features of the '<em>Instruction List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.emn.fil.boto.botoLang.impl.GotoImpl <em>Goto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emn.fil.boto.botoLang.impl.GotoImpl
   * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getGoto()
   * @generated
   */
  int GOTO = 3;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO__URL = 0;

  /**
   * The number of structural features of the '<em>Goto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.emn.fil.boto.botoLang.impl.ClickImpl <em>Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emn.fil.boto.botoLang.impl.ClickImpl
   * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getClick()
   * @generated
   */
  int CLICK = 4;

  /**
   * The feature id for the '<em><b>Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__OBJECT = 0;

  /**
   * The number of structural features of the '<em>Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.emn.fil.boto.botoLang.impl.FillImpl <em>Fill</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emn.fil.boto.botoLang.impl.FillImpl
   * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getFill()
   * @generated
   */
  int FILL = 5;

  /**
   * The feature id for the '<em><b>Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__OBJECT = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__VALUE = 1;

  /**
   * The number of structural features of the '<em>Fill</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.emn.fil.boto.botoLang.impl.CheckImpl <em>Check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emn.fil.boto.botoLang.impl.CheckImpl
   * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getCheck()
   * @generated
   */
  int CHECK = 6;

  /**
   * The feature id for the '<em><b>Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__OBJECT = 0;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__PREDICATE = 1;

  /**
   * The number of structural features of the '<em>Check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.emn.fil.boto.botoLang.impl.PredicateImpl <em>Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emn.fil.boto.botoLang.impl.PredicateImpl
   * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getPredicate()
   * @generated
   */
  int PREDICATE = 7;

  /**
   * The feature id for the '<em><b>Keyword</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__KEYWORD = 0;

  /**
   * The feature id for the '<em><b>Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__NOT = 1;

  /**
   * The feature id for the '<em><b>String Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__STRING_VALUE = 2;

  /**
   * The feature id for the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__VARIABLE = 3;

  /**
   * The feature id for the '<em><b>Second Keyword</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__SECOND_KEYWORD = 4;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__VALUE = 5;

  /**
   * The number of structural features of the '<em>Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.emn.fil.boto.botoLang.impl.PutImpl <em>Put</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emn.fil.boto.botoLang.impl.PutImpl
   * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getPut()
   * @generated
   */
  int PUT = 8;

  /**
   * The feature id for the '<em><b>Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT__OBJECT = 0;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT__STRING = 1;

  /**
   * The feature id for the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT__VARIABLE = 2;

  /**
   * The number of structural features of the '<em>Put</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.emn.fil.boto.botoLang.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emn.fil.boto.botoLang.impl.VariableImpl
   * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.emn.fil.boto.botoLang.impl.ObjectImpl <em>Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emn.fil.boto.botoLang.impl.ObjectImpl
   * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getObject()
   * @generated
   */
  int OBJECT = 10;

  /**
   * The feature id for the '<em><b>Html</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__HTML = 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__PARAM = 1;

  /**
   * The feature id for the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__VARIABLE = 2;

  /**
   * The number of structural features of the '<em>Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.emn.fil.boto.botoLang.impl.HtmlImpl <em>Html</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emn.fil.boto.botoLang.impl.HtmlImpl
   * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getHtml()
   * @generated
   */
  int HTML = 11;

  /**
   * The feature id for the '<em><b>Tag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTML__TAG = 0;

  /**
   * The number of structural features of the '<em>Html</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTML_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.emn.fil.boto.botoLang.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emn.fil.boto.botoLang.impl.FunctionImpl
   * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__VARIABLES = 1;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__INSTRUCTIONS = 2;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.emn.fil.boto.botoLang.impl.FunctionCallImpl <em>Function Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.emn.fil.boto.botoLang.impl.FunctionCallImpl
   * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getFunctionCall()
   * @generated
   */
  int FUNCTION_CALL = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL__NAME = 0;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL__VARIABLES = 1;

  /**
   * The number of structural features of the '<em>Function Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.emn.fil.boto.botoLang.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.emn.fil.boto.botoLang.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.emn.fil.boto.botoLang.Model#getFunctions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Functions</em>'.
   * @see org.emn.fil.boto.botoLang.Model#getFunctions()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Functions();

  /**
   * Returns the meta object for the containment reference list '{@link org.emn.fil.boto.botoLang.Model#getBrowsers <em>Browsers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Browsers</em>'.
   * @see org.emn.fil.boto.botoLang.Model#getBrowsers()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Browsers();

  /**
   * Returns the meta object for class '{@link org.emn.fil.boto.botoLang.Browser <em>Browser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Browser</em>'.
   * @see org.emn.fil.boto.botoLang.Browser
   * @generated
   */
  EClass getBrowser();

  /**
   * Returns the meta object for the attribute '{@link org.emn.fil.boto.botoLang.Browser#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.emn.fil.boto.botoLang.Browser#getName()
   * @see #getBrowser()
   * @generated
   */
  EAttribute getBrowser_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.emn.fil.boto.botoLang.Browser#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Instructions</em>'.
   * @see org.emn.fil.boto.botoLang.Browser#getInstructions()
   * @see #getBrowser()
   * @generated
   */
  EReference getBrowser_Instructions();

  /**
   * Returns the meta object for class '{@link org.emn.fil.boto.botoLang.InstructionList <em>Instruction List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction List</em>'.
   * @see org.emn.fil.boto.botoLang.InstructionList
   * @generated
   */
  EClass getInstructionList();

  /**
   * Returns the meta object for the containment reference list '{@link org.emn.fil.boto.botoLang.InstructionList#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see org.emn.fil.boto.botoLang.InstructionList#getInstructions()
   * @see #getInstructionList()
   * @generated
   */
  EReference getInstructionList_Instructions();

  /**
   * Returns the meta object for class '{@link org.emn.fil.boto.botoLang.Goto <em>Goto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Goto</em>'.
   * @see org.emn.fil.boto.botoLang.Goto
   * @generated
   */
  EClass getGoto();

  /**
   * Returns the meta object for the attribute '{@link org.emn.fil.boto.botoLang.Goto#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.emn.fil.boto.botoLang.Goto#getUrl()
   * @see #getGoto()
   * @generated
   */
  EAttribute getGoto_Url();

  /**
   * Returns the meta object for class '{@link org.emn.fil.boto.botoLang.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click</em>'.
   * @see org.emn.fil.boto.botoLang.Click
   * @generated
   */
  EClass getClick();

  /**
   * Returns the meta object for the containment reference '{@link org.emn.fil.boto.botoLang.Click#getObject <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Object</em>'.
   * @see org.emn.fil.boto.botoLang.Click#getObject()
   * @see #getClick()
   * @generated
   */
  EReference getClick_Object();

  /**
   * Returns the meta object for class '{@link org.emn.fil.boto.botoLang.Fill <em>Fill</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fill</em>'.
   * @see org.emn.fil.boto.botoLang.Fill
   * @generated
   */
  EClass getFill();

  /**
   * Returns the meta object for the containment reference '{@link org.emn.fil.boto.botoLang.Fill#getObject <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Object</em>'.
   * @see org.emn.fil.boto.botoLang.Fill#getObject()
   * @see #getFill()
   * @generated
   */
  EReference getFill_Object();

  /**
   * Returns the meta object for the attribute '{@link org.emn.fil.boto.botoLang.Fill#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.emn.fil.boto.botoLang.Fill#getValue()
   * @see #getFill()
   * @generated
   */
  EAttribute getFill_Value();

  /**
   * Returns the meta object for class '{@link org.emn.fil.boto.botoLang.Check <em>Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Check</em>'.
   * @see org.emn.fil.boto.botoLang.Check
   * @generated
   */
  EClass getCheck();

  /**
   * Returns the meta object for the containment reference '{@link org.emn.fil.boto.botoLang.Check#getObject <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Object</em>'.
   * @see org.emn.fil.boto.botoLang.Check#getObject()
   * @see #getCheck()
   * @generated
   */
  EReference getCheck_Object();

  /**
   * Returns the meta object for the containment reference '{@link org.emn.fil.boto.botoLang.Check#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate</em>'.
   * @see org.emn.fil.boto.botoLang.Check#getPredicate()
   * @see #getCheck()
   * @generated
   */
  EReference getCheck_Predicate();

  /**
   * Returns the meta object for class '{@link org.emn.fil.boto.botoLang.Predicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicate</em>'.
   * @see org.emn.fil.boto.botoLang.Predicate
   * @generated
   */
  EClass getPredicate();

  /**
   * Returns the meta object for the attribute '{@link org.emn.fil.boto.botoLang.Predicate#getKeyword <em>Keyword</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Keyword</em>'.
   * @see org.emn.fil.boto.botoLang.Predicate#getKeyword()
   * @see #getPredicate()
   * @generated
   */
  EAttribute getPredicate_Keyword();

  /**
   * Returns the meta object for the attribute '{@link org.emn.fil.boto.botoLang.Predicate#getNot <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Not</em>'.
   * @see org.emn.fil.boto.botoLang.Predicate#getNot()
   * @see #getPredicate()
   * @generated
   */
  EAttribute getPredicate_Not();

  /**
   * Returns the meta object for the attribute '{@link org.emn.fil.boto.botoLang.Predicate#getStringValue <em>String Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String Value</em>'.
   * @see org.emn.fil.boto.botoLang.Predicate#getStringValue()
   * @see #getPredicate()
   * @generated
   */
  EAttribute getPredicate_StringValue();

  /**
   * Returns the meta object for the reference '{@link org.emn.fil.boto.botoLang.Predicate#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable</em>'.
   * @see org.emn.fil.boto.botoLang.Predicate#getVariable()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_Variable();

  /**
   * Returns the meta object for the attribute '{@link org.emn.fil.boto.botoLang.Predicate#getSecondKeyword <em>Second Keyword</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Second Keyword</em>'.
   * @see org.emn.fil.boto.botoLang.Predicate#getSecondKeyword()
   * @see #getPredicate()
   * @generated
   */
  EAttribute getPredicate_SecondKeyword();

  /**
   * Returns the meta object for the attribute list '{@link org.emn.fil.boto.botoLang.Predicate#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.emn.fil.boto.botoLang.Predicate#getValue()
   * @see #getPredicate()
   * @generated
   */
  EAttribute getPredicate_Value();

  /**
   * Returns the meta object for class '{@link org.emn.fil.boto.botoLang.Put <em>Put</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Put</em>'.
   * @see org.emn.fil.boto.botoLang.Put
   * @generated
   */
  EClass getPut();

  /**
   * Returns the meta object for the containment reference '{@link org.emn.fil.boto.botoLang.Put#getObject <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Object</em>'.
   * @see org.emn.fil.boto.botoLang.Put#getObject()
   * @see #getPut()
   * @generated
   */
  EReference getPut_Object();

  /**
   * Returns the meta object for the attribute '{@link org.emn.fil.boto.botoLang.Put#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see org.emn.fil.boto.botoLang.Put#getString()
   * @see #getPut()
   * @generated
   */
  EAttribute getPut_String();

  /**
   * Returns the meta object for the containment reference '{@link org.emn.fil.boto.botoLang.Put#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Variable</em>'.
   * @see org.emn.fil.boto.botoLang.Put#getVariable()
   * @see #getPut()
   * @generated
   */
  EReference getPut_Variable();

  /**
   * Returns the meta object for class '{@link org.emn.fil.boto.botoLang.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.emn.fil.boto.botoLang.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.emn.fil.boto.botoLang.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.emn.fil.boto.botoLang.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link org.emn.fil.boto.botoLang.Object <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object</em>'.
   * @see org.emn.fil.boto.botoLang.Object
   * @generated
   */
  EClass getObject();

  /**
   * Returns the meta object for the containment reference '{@link org.emn.fil.boto.botoLang.Object#getHtml <em>Html</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Html</em>'.
   * @see org.emn.fil.boto.botoLang.Object#getHtml()
   * @see #getObject()
   * @generated
   */
  EReference getObject_Html();

  /**
   * Returns the meta object for the attribute '{@link org.emn.fil.boto.botoLang.Object#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Param</em>'.
   * @see org.emn.fil.boto.botoLang.Object#getParam()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_Param();

  /**
   * Returns the meta object for the reference '{@link org.emn.fil.boto.botoLang.Object#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable</em>'.
   * @see org.emn.fil.boto.botoLang.Object#getVariable()
   * @see #getObject()
   * @generated
   */
  EReference getObject_Variable();

  /**
   * Returns the meta object for class '{@link org.emn.fil.boto.botoLang.Html <em>Html</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Html</em>'.
   * @see org.emn.fil.boto.botoLang.Html
   * @generated
   */
  EClass getHtml();

  /**
   * Returns the meta object for the attribute '{@link org.emn.fil.boto.botoLang.Html#getTag <em>Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tag</em>'.
   * @see org.emn.fil.boto.botoLang.Html#getTag()
   * @see #getHtml()
   * @generated
   */
  EAttribute getHtml_Tag();

  /**
   * Returns the meta object for class '{@link org.emn.fil.boto.botoLang.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see org.emn.fil.boto.botoLang.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link org.emn.fil.boto.botoLang.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.emn.fil.boto.botoLang.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.emn.fil.boto.botoLang.Function#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see org.emn.fil.boto.botoLang.Function#getVariables()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Variables();

  /**
   * Returns the meta object for the containment reference '{@link org.emn.fil.boto.botoLang.Function#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Instructions</em>'.
   * @see org.emn.fil.boto.botoLang.Function#getInstructions()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Instructions();

  /**
   * Returns the meta object for class '{@link org.emn.fil.boto.botoLang.FunctionCall <em>Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Call</em>'.
   * @see org.emn.fil.boto.botoLang.FunctionCall
   * @generated
   */
  EClass getFunctionCall();

  /**
   * Returns the meta object for the reference '{@link org.emn.fil.boto.botoLang.FunctionCall#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see org.emn.fil.boto.botoLang.FunctionCall#getName()
   * @see #getFunctionCall()
   * @generated
   */
  EReference getFunctionCall_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.emn.fil.boto.botoLang.FunctionCall#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see org.emn.fil.boto.botoLang.FunctionCall#getVariables()
   * @see #getFunctionCall()
   * @generated
   */
  EReference getFunctionCall_Variables();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BotoLangFactory getBotoLangFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.emn.fil.boto.botoLang.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emn.fil.boto.botoLang.impl.ModelImpl
     * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Functions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__FUNCTIONS = eINSTANCE.getModel_Functions();

    /**
     * The meta object literal for the '<em><b>Browsers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__BROWSERS = eINSTANCE.getModel_Browsers();

    /**
     * The meta object literal for the '{@link org.emn.fil.boto.botoLang.impl.BrowserImpl <em>Browser</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emn.fil.boto.botoLang.impl.BrowserImpl
     * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getBrowser()
     * @generated
     */
    EClass BROWSER = eINSTANCE.getBrowser();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BROWSER__NAME = eINSTANCE.getBrowser_Name();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BROWSER__INSTRUCTIONS = eINSTANCE.getBrowser_Instructions();

    /**
     * The meta object literal for the '{@link org.emn.fil.boto.botoLang.impl.InstructionListImpl <em>Instruction List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emn.fil.boto.botoLang.impl.InstructionListImpl
     * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getInstructionList()
     * @generated
     */
    EClass INSTRUCTION_LIST = eINSTANCE.getInstructionList();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTION_LIST__INSTRUCTIONS = eINSTANCE.getInstructionList_Instructions();

    /**
     * The meta object literal for the '{@link org.emn.fil.boto.botoLang.impl.GotoImpl <em>Goto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emn.fil.boto.botoLang.impl.GotoImpl
     * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getGoto()
     * @generated
     */
    EClass GOTO = eINSTANCE.getGoto();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOTO__URL = eINSTANCE.getGoto_Url();

    /**
     * The meta object literal for the '{@link org.emn.fil.boto.botoLang.impl.ClickImpl <em>Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emn.fil.boto.botoLang.impl.ClickImpl
     * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getClick()
     * @generated
     */
    EClass CLICK = eINSTANCE.getClick();

    /**
     * The meta object literal for the '<em><b>Object</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLICK__OBJECT = eINSTANCE.getClick_Object();

    /**
     * The meta object literal for the '{@link org.emn.fil.boto.botoLang.impl.FillImpl <em>Fill</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emn.fil.boto.botoLang.impl.FillImpl
     * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getFill()
     * @generated
     */
    EClass FILL = eINSTANCE.getFill();

    /**
     * The meta object literal for the '<em><b>Object</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILL__OBJECT = eINSTANCE.getFill_Object();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL__VALUE = eINSTANCE.getFill_Value();

    /**
     * The meta object literal for the '{@link org.emn.fil.boto.botoLang.impl.CheckImpl <em>Check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emn.fil.boto.botoLang.impl.CheckImpl
     * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getCheck()
     * @generated
     */
    EClass CHECK = eINSTANCE.getCheck();

    /**
     * The meta object literal for the '<em><b>Object</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK__OBJECT = eINSTANCE.getCheck_Object();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK__PREDICATE = eINSTANCE.getCheck_Predicate();

    /**
     * The meta object literal for the '{@link org.emn.fil.boto.botoLang.impl.PredicateImpl <em>Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emn.fil.boto.botoLang.impl.PredicateImpl
     * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getPredicate()
     * @generated
     */
    EClass PREDICATE = eINSTANCE.getPredicate();

    /**
     * The meta object literal for the '<em><b>Keyword</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICATE__KEYWORD = eINSTANCE.getPredicate_Keyword();

    /**
     * The meta object literal for the '<em><b>Not</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICATE__NOT = eINSTANCE.getPredicate_Not();

    /**
     * The meta object literal for the '<em><b>String Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICATE__STRING_VALUE = eINSTANCE.getPredicate_StringValue();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__VARIABLE = eINSTANCE.getPredicate_Variable();

    /**
     * The meta object literal for the '<em><b>Second Keyword</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICATE__SECOND_KEYWORD = eINSTANCE.getPredicate_SecondKeyword();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICATE__VALUE = eINSTANCE.getPredicate_Value();

    /**
     * The meta object literal for the '{@link org.emn.fil.boto.botoLang.impl.PutImpl <em>Put</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emn.fil.boto.botoLang.impl.PutImpl
     * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getPut()
     * @generated
     */
    EClass PUT = eINSTANCE.getPut();

    /**
     * The meta object literal for the '<em><b>Object</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUT__OBJECT = eINSTANCE.getPut_Object();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PUT__STRING = eINSTANCE.getPut_String();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUT__VARIABLE = eINSTANCE.getPut_Variable();

    /**
     * The meta object literal for the '{@link org.emn.fil.boto.botoLang.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emn.fil.boto.botoLang.impl.VariableImpl
     * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link org.emn.fil.boto.botoLang.impl.ObjectImpl <em>Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emn.fil.boto.botoLang.impl.ObjectImpl
     * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getObject()
     * @generated
     */
    EClass OBJECT = eINSTANCE.getObject();

    /**
     * The meta object literal for the '<em><b>Html</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT__HTML = eINSTANCE.getObject_Html();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__PARAM = eINSTANCE.getObject_Param();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT__VARIABLE = eINSTANCE.getObject_Variable();

    /**
     * The meta object literal for the '{@link org.emn.fil.boto.botoLang.impl.HtmlImpl <em>Html</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emn.fil.boto.botoLang.impl.HtmlImpl
     * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getHtml()
     * @generated
     */
    EClass HTML = eINSTANCE.getHtml();

    /**
     * The meta object literal for the '<em><b>Tag</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HTML__TAG = eINSTANCE.getHtml_Tag();

    /**
     * The meta object literal for the '{@link org.emn.fil.boto.botoLang.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emn.fil.boto.botoLang.impl.FunctionImpl
     * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__VARIABLES = eINSTANCE.getFunction_Variables();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__INSTRUCTIONS = eINSTANCE.getFunction_Instructions();

    /**
     * The meta object literal for the '{@link org.emn.fil.boto.botoLang.impl.FunctionCallImpl <em>Function Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.emn.fil.boto.botoLang.impl.FunctionCallImpl
     * @see org.emn.fil.boto.botoLang.impl.BotoLangPackageImpl#getFunctionCall()
     * @generated
     */
    EClass FUNCTION_CALL = eINSTANCE.getFunctionCall();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL__NAME = eINSTANCE.getFunctionCall_Name();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL__VARIABLES = eINSTANCE.getFunctionCall_Variables();

  }

} //BotoLangPackage
