/**
 * generated by Xtext 2.10.0
 */
package org.emn.fil.boto.botoLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Check</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emn.fil.boto.botoLang.Check#getObject <em>Object</em>}</li>
 *   <li>{@link org.emn.fil.boto.botoLang.Check#getPredicate <em>Predicate</em>}</li>
 * </ul>
 *
 * @see org.emn.fil.boto.botoLang.BotoLangPackage#getCheck()
 * @model
 * @generated
 */
public interface Check extends EObject
{
  /**
   * Returns the value of the '<em><b>Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Object</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object</em>' containment reference.
   * @see #setObject(org.emn.fil.boto.botoLang.Object)
   * @see org.emn.fil.boto.botoLang.BotoLangPackage#getCheck_Object()
   * @model containment="true"
   * @generated
   */
  org.emn.fil.boto.botoLang.Object getObject();

  /**
   * Sets the value of the '{@link org.emn.fil.boto.botoLang.Check#getObject <em>Object</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object</em>' containment reference.
   * @see #getObject()
   * @generated
   */
  void setObject(org.emn.fil.boto.botoLang.Object value);

  /**
   * Returns the value of the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Predicate</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicate</em>' containment reference.
   * @see #setPredicate(Predicate)
   * @see org.emn.fil.boto.botoLang.BotoLangPackage#getCheck_Predicate()
   * @model containment="true"
   * @generated
   */
  Predicate getPredicate();

  /**
   * Sets the value of the '{@link org.emn.fil.boto.botoLang.Check#getPredicate <em>Predicate</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predicate</em>' containment reference.
   * @see #getPredicate()
   * @generated
   */
  void setPredicate(Predicate value);

} // Check
