/**
 * generated by Xtext 2.10.0
 */
package org.emn.fil.boto.botoLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emn.fil.boto.botoLang.Model#getFunctions <em>Functions</em>}</li>
 *   <li>{@link org.emn.fil.boto.botoLang.Model#getBrowsers <em>Browsers</em>}</li>
 * </ul>
 *
 * @see org.emn.fil.boto.botoLang.BotoLangPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Functions</b></em>' containment reference list.
   * The list contents are of type {@link org.emn.fil.boto.botoLang.Function}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Functions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functions</em>' containment reference list.
   * @see org.emn.fil.boto.botoLang.BotoLangPackage#getModel_Functions()
   * @model containment="true"
   * @generated
   */
  EList<Function> getFunctions();

  /**
   * Returns the value of the '<em><b>Browsers</b></em>' containment reference list.
   * The list contents are of type {@link org.emn.fil.boto.botoLang.Browser}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Browsers</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Browsers</em>' containment reference list.
   * @see org.emn.fil.boto.botoLang.BotoLangPackage#getModel_Browsers()
   * @model containment="true"
   * @generated
   */
  EList<Browser> getBrowsers();

} // Model
