/*
 * generated by Xtext 2.10.0
 */
package org.emn.fil.boto.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BotoLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/emn/fil/boto/parser/antlr/internal/InternalBotoLang.tokens");
	}
}
