/*
 * generated by Xtext 2.10.0
 */
package org.emn.fil.boto.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.emn.fil.boto.parser.antlr.internal.InternalBotoLangParser;
import org.emn.fil.boto.services.BotoLangGrammarAccess;

public class BotoLangParser extends AbstractAntlrParser {

	@Inject
	private BotoLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBotoLangParser createParser(XtextTokenStream stream) {
		return new InternalBotoLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public BotoLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BotoLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
