/*
 * generated by Xtext 2.10.0
 */
package org.emn.fil.boto.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.emn.fil.boto.ui.internal.BotoActivator;

public class BotoLangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BotoActivator.getInstance().getInjector("org.emn.fil.boto.BotoLang");
	}

}
