/**
 * generated by Xtext 2.10.0
 */
package org.emn.fil.boto.validation;

import org.emn.fil.boto.validation.AbstractBotoLangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BotoLangValidator extends AbstractBotoLangValidator {
}
