/*
 * generated by Xtext 2.10.0
 */
package org.emn.fil.boto.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBotoLangScopeProvider extends DelegatingScopeProvider {
}
