/**
 * generated by Xtext 2.10.0
 */
package org.emn.fil.boto;

import org.emn.fil.boto.BotoLangStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BotoLangStandaloneSetup extends BotoLangStandaloneSetupGenerated {
  public static void doSetup() {
    BotoLangStandaloneSetup _botoLangStandaloneSetup = new BotoLangStandaloneSetup();
    _botoLangStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
