/**
 * generated by Xtext 2.10.0
 */
package org.emn.fil.boto;

import org.emn.fil.boto.AbstractBotoLangRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class BotoLangRuntimeModule extends AbstractBotoLangRuntimeModule {
}
